### ISSUE TITLE
Build errors - which DPDK version to use?

### ISSUE THREAD

**Issue by thealexcons** [gamemann/The-DPDK-Examples#1]
Hi there,

Firstly, thanks for creating this repository with examples. I was just wondering if you could publish which DPDK version your examples are using, since I am getting some build errors for some undefined macros and field names. I believe some macros you are using have been renamed in later versions of DPDK.

**Comment by gamemann** [comment]
Hey! I don't recall what version I was using since it was a while ago, but I did update The DPDK Common repository a few months ago due to an [error](https://github.com/gamemann/The-DPDK-Common/commit/1eb7b9675dcb18bcbebc2f109913f79d4ea884d7) similar to what you mentioned. I forgot to update to the latest commit in the sub-module for this repository which is now completed.

Can you try to build the DPDK examples now after pulling the latest changes?

**Comment by thealexcons** [comment]
Thanks, seems to be building now!
